# docker-compose.yml
version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: jornada-reino-app
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: app
      SERVICE_TAGS: dev
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
      - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - jornada-reino-network
    depends_on:
      - db
    ports:
      - "8000:8000"  # Para rodar com php artisan serve

  db:
    image: mysql:8.0
    container_name: jornada-reino-db
    restart: unless-stopped
    tty: true
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: reino
      MYSQL_USER: reino_user
      MYSQL_PASSWORD: Lav8@472
      MYSQL_ROOT_PASSWORD: rootpassword  # opcional, mas útil para admin
    volumes:
      - ./docker/mysql:/var/lib/mysql
    networks:
      - jornada-reino-network

networks:
  jornada-reino-network:
    driver: bridge
